controller_list:
  - name: fake_gripper_fingers_controller
    type: $(arg fake_execution_type)
    joints:
      - Slider01
      - Slider02
initial:  # Define initial robot poses per group
  - group: gripper_fingers
    pose: home