gripper_fingers_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - Slider01
    - Slider02
  gains:
    Slider01: {p: 5000, i: 10, d: 1, i_clamp: 1}
    Slider02: {p: 5000, i: 10, d: 1, i_clamp: 1}